---
jobs:
  include:
    - stage: Build Database uploader
      script:
        - cd $TRAVIS_BUILD_DIR && ./script/build-database-uploader.sh
    - stage: Build XML Validator
      script:
        - set -e && cd $TRAVIS_BUILD_DIR/invoices-xml-validator && docker build --rm -t aifagovit/invoices-xml-validator:latest . && set +e
services:
  - docker
sudo: required
