---
jobs:
  include:
    - stage: Build Database uploader
      script:
        - ./script/test-dockerfiles.sh --docker-context-path=.
        - ./script/build-database-uploader.sh
services:
  - docker
sudo: required
