FROM maven:3.5.0-jdk-8-alpine

ENV WORKDIR /usr/app/aifa-gov-it/database-uploader/
WORKDIR $WORKDIR

COPY ./lib/ $WORKDIR/lib/
COPY install-dependencies.sh install-dependencies.sh

RUN chmod a+x install-dependencies.sh
RUN ./install-dependencies.sh
