//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiPagamentoType", propOrder = { "condizioniPagamento", "dettaglioPagamento" })
public class DatiPagamentoType {

	@XmlElement(name = "CondizioniPagamento", required = true)
	@XmlSchemaType(name = "string")
	protected CondizioniPagamentoType condizioniPagamento;
	@XmlElement(name = "DettaglioPagamento", required = true)
	protected List<DettaglioPagamentoType> dettaglioPagamento;

	public CondizioniPagamentoType getCondizioniPagamento() {
		return condizioniPagamento;
	}

	public void setCondizioniPagamento(CondizioniPagamentoType value) {
		this.condizioniPagamento = value;
	}

	public List<DettaglioPagamentoType> getDettaglioPagamento() {
		if (dettaglioPagamento == null) {
			dettaglioPagamento = new ArrayList<DettaglioPagamentoType>();
		}
		return this.dettaglioPagamento;
	}

}
