//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiTrasportoType", propOrder = { "datiAnagraficiVettore", "mezzoTrasporto", "causaleTrasporto",
		"numeroColli", "descrizione", "unitaMisuraPeso", "pesoLordo", "pesoNetto", "dataOraRitiro",
		"dataInizioTrasporto", "tipoResa", "indirizzoResa", "dataOraConsegna" })
public class DatiTrasportoType {

	@XmlElement(name = "DatiAnagraficiVettore")
	protected DatiAnagraficiVettoreType datiAnagraficiVettore;
	@XmlElement(name = "MezzoTrasporto")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String mezzoTrasporto;
	@XmlElement(name = "CausaleTrasporto")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String causaleTrasporto;
	@XmlElement(name = "NumeroColli")
	@XmlSchemaType(name = "integer")
	protected Integer numeroColli;
	@XmlElement(name = "Descrizione")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String descrizione;
	@XmlElement(name = "UnitaMisuraPeso")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String unitaMisuraPeso;
	@XmlElement(name = "PesoLordo")
	protected BigDecimal pesoLordo;
	@XmlElement(name = "PesoNetto")
	protected BigDecimal pesoNetto;
	@XmlElement(name = "DataOraRitiro")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar dataOraRitiro;
	@XmlElement(name = "DataInizioTrasporto")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataInizioTrasporto;
	@XmlElement(name = "TipoResa")
	protected String tipoResa;
	@XmlElement(name = "IndirizzoResa")
	protected IndirizzoType indirizzoResa;
	@XmlElement(name = "DataOraConsegna")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar dataOraConsegna;

	public DatiAnagraficiVettoreType getDatiAnagraficiVettore() {
		return datiAnagraficiVettore;
	}

	public void setDatiAnagraficiVettore(DatiAnagraficiVettoreType value) {
		this.datiAnagraficiVettore = value;
	}

	public String getMezzoTrasporto() {
		return mezzoTrasporto;
	}

	public void setMezzoTrasporto(String value) {
		this.mezzoTrasporto = value;
	}

	public String getCausaleTrasporto() {
		return causaleTrasporto;
	}

	public void setCausaleTrasporto(String value) {
		this.causaleTrasporto = value;
	}

	public Integer getNumeroColli() {
		return numeroColli;
	}

	public void setNumeroColli(Integer value) {
		this.numeroColli = value;
	}

	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String value) {
		this.descrizione = value;
	}

	public String getUnitaMisuraPeso() {
		return unitaMisuraPeso;
	}

	public void setUnitaMisuraPeso(String value) {
		this.unitaMisuraPeso = value;
	}

	public BigDecimal getPesoLordo() {
		return pesoLordo;
	}

	public void setPesoLordo(BigDecimal value) {
		this.pesoLordo = value;
	}

	public BigDecimal getPesoNetto() {
		return pesoNetto;
	}

	public void setPesoNetto(BigDecimal value) {
		this.pesoNetto = value;
	}

	public XMLGregorianCalendar getDataOraRitiro() {
		return dataOraRitiro;
	}

	public void setDataOraRitiro(XMLGregorianCalendar value) {
		this.dataOraRitiro = value;
	}

	public XMLGregorianCalendar getDataInizioTrasporto() {
		return dataInizioTrasporto;
	}

	public void setDataInizioTrasporto(XMLGregorianCalendar value) {
		this.dataInizioTrasporto = value;
	}

	public String getTipoResa() {
		return tipoResa;
	}

	public void setTipoResa(String value) {
		this.tipoResa = value;
	}

	public IndirizzoType getIndirizzoResa() {
		return indirizzoResa;
	}

	public void setIndirizzoResa(IndirizzoType value) {
		this.indirizzoResa = value;
	}

	public XMLGregorianCalendar getDataOraConsegna() {
		return dataOraConsegna;
	}

	public void setDataOraConsegna(XMLGregorianCalendar value) {
		this.dataOraConsegna = value;
	}

}
