//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiRiepilogoType", propOrder = { "aliquotaIVA", "natura", "speseAccessorie", "arrotondamento",
		"imponibileImporto", "imposta", "esigibilitaIVA", "riferimentoNormativo" })
public class DatiRiepilogoType {

	@XmlElement(name = "AliquotaIVA", required = true)
	protected BigDecimal aliquotaIVA;
	@XmlElement(name = "Natura")
	@XmlSchemaType(name = "string")
	protected NaturaType natura;
	@XmlElement(name = "SpeseAccessorie")
	protected BigDecimal speseAccessorie;
	@XmlElement(name = "Arrotondamento")
	protected BigDecimal arrotondamento;
	@XmlElement(name = "ImponibileImporto", required = true)
	protected BigDecimal imponibileImporto;
	@XmlElement(name = "Imposta", required = true)
	protected BigDecimal imposta;
	@XmlElement(name = "EsigibilitaIVA")
	@XmlSchemaType(name = "string")
	protected EsigibilitaIVAType esigibilitaIVA;
	@XmlElement(name = "RiferimentoNormativo")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String riferimentoNormativo;

	public BigDecimal getAliquotaIVA() {
		return aliquotaIVA;
	}

	public void setAliquotaIVA(BigDecimal value) {
		this.aliquotaIVA = value;
	}

	public NaturaType getNatura() {
		return natura;
	}

	public void setNatura(NaturaType value) {
		this.natura = value;
	}

	public BigDecimal getSpeseAccessorie() {
		return speseAccessorie;
	}

	public void setSpeseAccessorie(BigDecimal value) {
		this.speseAccessorie = value;
	}

	public BigDecimal getArrotondamento() {
		return arrotondamento;
	}

	public void setArrotondamento(BigDecimal value) {
		this.arrotondamento = value;
	}

	public BigDecimal getImponibileImporto() {
		return imponibileImporto;
	}

	public void setImponibileImporto(BigDecimal value) {
		this.imponibileImporto = value;
	}

	public BigDecimal getImposta() {
		return imposta;
	}

	public void setImposta(BigDecimal value) {
		this.imposta = value;
	}

	public EsigibilitaIVAType getEsigibilitaIVA() {
		return esigibilitaIVA;
	}

	public void setEsigibilitaIVA(EsigibilitaIVAType value) {
		this.esigibilitaIVA = value;
	}

	public String getRiferimentoNormativo() {
		return riferimentoNormativo;
	}

	public void setRiferimentoNormativo(String value) {
		this.riferimentoNormativo = value;
	}

}
