//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiGeneraliType", propOrder = { "datiGeneraliDocumento", "datiOrdineAcquisto", "datiContratto",
		"datiConvenzione", "datiRicezione", "datiFattureCollegate", "datiSAL", "datiDDT", "datiTrasporto",
		"fatturaPrincipale" })
public class DatiGeneraliType {

	@XmlElement(name = "DatiGeneraliDocumento", required = true)
	protected DatiGeneraliDocumentoType datiGeneraliDocumento;
	@XmlElement(name = "DatiOrdineAcquisto")
	protected List<DatiDocumentiCorrelatiType> datiOrdineAcquisto;
	@XmlElement(name = "DatiContratto")
	protected List<DatiDocumentiCorrelatiType> datiContratto;
	@XmlElement(name = "DatiConvenzione")
	protected List<DatiDocumentiCorrelatiType> datiConvenzione;
	@XmlElement(name = "DatiRicezione")
	protected List<DatiDocumentiCorrelatiType> datiRicezione;
	@XmlElement(name = "DatiFattureCollegate")
	protected List<DatiDocumentiCorrelatiType> datiFattureCollegate;
	@XmlElement(name = "DatiSAL")
	protected List<DatiSALType> datiSAL;
	@XmlElement(name = "DatiDDT")
	protected List<DatiDDTType> datiDDT;
	@XmlElement(name = "DatiTrasporto")
	protected DatiTrasportoType datiTrasporto;
	@XmlElement(name = "FatturaPrincipale")
	protected FatturaPrincipaleType fatturaPrincipale;

	public DatiGeneraliDocumentoType getDatiGeneraliDocumento() {
		return datiGeneraliDocumento;
	}

	public void setDatiGeneraliDocumento(DatiGeneraliDocumentoType value) {
		this.datiGeneraliDocumento = value;
	}

	public List<DatiDocumentiCorrelatiType> getDatiOrdineAcquisto() {
		if (datiOrdineAcquisto == null) {
			datiOrdineAcquisto = new ArrayList<DatiDocumentiCorrelatiType>();
		}
		return this.datiOrdineAcquisto;
	}

	public List<DatiDocumentiCorrelatiType> getDatiContratto() {
		if (datiContratto == null) {
			datiContratto = new ArrayList<DatiDocumentiCorrelatiType>();
		}
		return this.datiContratto;
	}

	public List<DatiDocumentiCorrelatiType> getDatiConvenzione() {
		if (datiConvenzione == null) {
			datiConvenzione = new ArrayList<DatiDocumentiCorrelatiType>();
		}
		return this.datiConvenzione;
	}

	public List<DatiDocumentiCorrelatiType> getDatiRicezione() {
		if (datiRicezione == null) {
			datiRicezione = new ArrayList<DatiDocumentiCorrelatiType>();
		}
		return this.datiRicezione;
	}

	public List<DatiDocumentiCorrelatiType> getDatiFattureCollegate() {
		if (datiFattureCollegate == null) {
			datiFattureCollegate = new ArrayList<DatiDocumentiCorrelatiType>();
		}
		return this.datiFattureCollegate;
	}

	public List<DatiSALType> getDatiSAL() {
		if (datiSAL == null) {
			datiSAL = new ArrayList<DatiSALType>();
		}
		return this.datiSAL;
	}

	public List<DatiDDTType> getDatiDDT() {
		if (datiDDT == null) {
			datiDDT = new ArrayList<DatiDDTType>();
		}
		return this.datiDDT;
	}

	public DatiTrasportoType getDatiTrasporto() {
		return datiTrasporto;
	}

	public void setDatiTrasporto(DatiTrasportoType value) {
		this.datiTrasporto = value;
	}

	public FatturaPrincipaleType getFatturaPrincipale() {
		return fatturaPrincipale;
	}

	public void setFatturaPrincipale(FatturaPrincipaleType value) {
		this.fatturaPrincipale = value;
	}

}
