//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiRitenutaType", propOrder = { "tipoRitenuta", "importoRitenuta", "aliquotaRitenuta",
		"causalePagamento" })
public class DatiRitenutaType {

	@XmlElement(name = "TipoRitenuta", required = true)
	@XmlSchemaType(name = "string")
	protected TipoRitenutaType tipoRitenuta;
	@XmlElement(name = "ImportoRitenuta", required = true)
	protected BigDecimal importoRitenuta;
	@XmlElement(name = "AliquotaRitenuta", required = true)
	protected BigDecimal aliquotaRitenuta;
	@XmlElement(name = "CausalePagamento", required = true)
	@XmlSchemaType(name = "string")
	protected CausalePagamentoType causalePagamento;

	public TipoRitenutaType getTipoRitenuta() {
		return tipoRitenuta;
	}

	public void setTipoRitenuta(TipoRitenutaType value) {
		this.tipoRitenuta = value;
	}

	public BigDecimal getImportoRitenuta() {
		return importoRitenuta;
	}

	public void setImportoRitenuta(BigDecimal value) {
		this.importoRitenuta = value;
	}

	public BigDecimal getAliquotaRitenuta() {
		return aliquotaRitenuta;
	}

	public void setAliquotaRitenuta(BigDecimal value) {
		this.aliquotaRitenuta = value;
	}

	public CausalePagamentoType getCausalePagamento() {
		return causalePagamento;
	}

	public void setCausalePagamento(CausalePagamentoType value) {
		this.causalePagamento = value;
	}

}
