//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiTrasmissioneType", propOrder = { "idTrasmittente", "progressivoInvio", "formatoTrasmissione",
		"codiceDestinatario", "contattiTrasmittente", "pecDestinatario" })
public class DatiTrasmissioneType {

	@XmlElement(name = "IdTrasmittente", required = true)
	protected IdFiscaleType idTrasmittente;
	@XmlElement(name = "ProgressivoInvio", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String progressivoInvio;
	@XmlElement(name = "FormatoTrasmissione", required = true)
	@XmlSchemaType(name = "string")
	protected FormatoTrasmissioneType formatoTrasmissione;
	@XmlElement(name = "CodiceDestinatario", required = true)
	protected String codiceDestinatario;
	@XmlElement(name = "ContattiTrasmittente")
	protected ContattiTrasmittenteType contattiTrasmittente;
	@XmlElement(name = "PECDestinatario")
	protected String pecDestinatario;

	public IdFiscaleType getIdTrasmittente() {
		return idTrasmittente;
	}

	public void setIdTrasmittente(IdFiscaleType value) {
		this.idTrasmittente = value;
	}

	public String getProgressivoInvio() {
		return progressivoInvio;
	}

	public void setProgressivoInvio(String value) {
		this.progressivoInvio = value;
	}

	public FormatoTrasmissioneType getFormatoTrasmissione() {
		return formatoTrasmissione;
	}

	public void setFormatoTrasmissione(FormatoTrasmissioneType value) {
		this.formatoTrasmissione = value;
	}

	public String getCodiceDestinatario() {
		return codiceDestinatario;
	}

	public void setCodiceDestinatario(String value) {
		this.codiceDestinatario = value;
	}

	public ContattiTrasmittenteType getContattiTrasmittente() {
		return contattiTrasmittente;
	}

	public void setContattiTrasmittente(ContattiTrasmittenteType value) {
		this.contattiTrasmittente = value;
	}

	public String getPECDestinatario() {
		return pecDestinatario;
	}

	public void setPECDestinatario(String value) {
		this.pecDestinatario = value;
	}

}
