//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DettaglioPagamentoType", propOrder = { "beneficiario", "modalitaPagamento",
		"dataRiferimentoTerminiPagamento", "giorniTerminiPagamento", "dataScadenzaPagamento", "importoPagamento",
		"codUfficioPostale", "cognomeQuietanzante", "nomeQuietanzante", "cfQuietanzante", "titoloQuietanzante",
		"istitutoFinanziario", "iban", "abi", "cab", "bic", "scontoPagamentoAnticipato",
		"dataLimitePagamentoAnticipato", "penalitaPagamentiRitardati", "dataDecorrenzaPenale", "codicePagamento" })
public class DettaglioPagamentoType {

	@XmlElement(name = "Beneficiario")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String beneficiario;
	@XmlElement(name = "ModalitaPagamento", required = true)
	@XmlSchemaType(name = "string")
	protected ModalitaPagamentoType modalitaPagamento;
	@XmlElement(name = "DataRiferimentoTerminiPagamento")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataRiferimentoTerminiPagamento;
	@XmlElement(name = "GiorniTerminiPagamento")
	@XmlSchemaType(name = "integer")
	protected Integer giorniTerminiPagamento;
	@XmlElement(name = "DataScadenzaPagamento")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataScadenzaPagamento;
	@XmlElement(name = "ImportoPagamento", required = true)
	protected BigDecimal importoPagamento;
	@XmlElement(name = "CodUfficioPostale")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String codUfficioPostale;
	@XmlElement(name = "CognomeQuietanzante")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String cognomeQuietanzante;
	@XmlElement(name = "NomeQuietanzante")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String nomeQuietanzante;
	@XmlElement(name = "CFQuietanzante")
	protected String cfQuietanzante;
	@XmlElement(name = "TitoloQuietanzante")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String titoloQuietanzante;
	@XmlElement(name = "IstitutoFinanziario")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String istitutoFinanziario;
	@XmlElement(name = "IBAN")
	protected String iban;
	@XmlElement(name = "ABI")
	protected String abi;
	@XmlElement(name = "CAB")
	protected String cab;
	@XmlElement(name = "BIC")
	protected String bic;
	@XmlElement(name = "ScontoPagamentoAnticipato")
	protected BigDecimal scontoPagamentoAnticipato;
	@XmlElement(name = "DataLimitePagamentoAnticipato")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataLimitePagamentoAnticipato;
	@XmlElement(name = "PenalitaPagamentiRitardati")
	protected BigDecimal penalitaPagamentiRitardati;
	@XmlElement(name = "DataDecorrenzaPenale")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataDecorrenzaPenale;
	@XmlElement(name = "CodicePagamento")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String codicePagamento;

	public String getBeneficiario() {
		return beneficiario;
	}

	public void setBeneficiario(String value) {
		this.beneficiario = value;
	}

	public ModalitaPagamentoType getModalitaPagamento() {
		return modalitaPagamento;
	}

	public void setModalitaPagamento(ModalitaPagamentoType value) {
		this.modalitaPagamento = value;
	}

	public XMLGregorianCalendar getDataRiferimentoTerminiPagamento() {
		return dataRiferimentoTerminiPagamento;
	}

	public void setDataRiferimentoTerminiPagamento(XMLGregorianCalendar value) {
		this.dataRiferimentoTerminiPagamento = value;
	}

	public Integer getGiorniTerminiPagamento() {
		return giorniTerminiPagamento;
	}

	public void setGiorniTerminiPagamento(Integer value) {
		this.giorniTerminiPagamento = value;
	}

	public XMLGregorianCalendar getDataScadenzaPagamento() {
		return dataScadenzaPagamento;
	}

	public void setDataScadenzaPagamento(XMLGregorianCalendar value) {
		this.dataScadenzaPagamento = value;
	}

	public BigDecimal getImportoPagamento() {
		return importoPagamento;
	}

	public void setImportoPagamento(BigDecimal value) {
		this.importoPagamento = value;
	}

	public String getCodUfficioPostale() {
		return codUfficioPostale;
	}

	public void setCodUfficioPostale(String value) {
		this.codUfficioPostale = value;
	}

	public String getCognomeQuietanzante() {
		return cognomeQuietanzante;
	}

	public void setCognomeQuietanzante(String value) {
		this.cognomeQuietanzante = value;
	}

	public String getNomeQuietanzante() {
		return nomeQuietanzante;
	}

	public void setNomeQuietanzante(String value) {
		this.nomeQuietanzante = value;
	}

	public String getCFQuietanzante() {
		return cfQuietanzante;
	}

	public void setCFQuietanzante(String value) {
		this.cfQuietanzante = value;
	}

	public String getTitoloQuietanzante() {
		return titoloQuietanzante;
	}

	public void setTitoloQuietanzante(String value) {
		this.titoloQuietanzante = value;
	}

	public String getIstitutoFinanziario() {
		return istitutoFinanziario;
	}

	public void setIstitutoFinanziario(String value) {
		this.istitutoFinanziario = value;
	}

	public String getIBAN() {
		return iban;
	}

	public void setIBAN(String value) {
		this.iban = value;
	}

	public String getABI() {
		return abi;
	}

	public void setABI(String value) {
		this.abi = value;
	}

	public String getCAB() {
		return cab;
	}

	public void setCAB(String value) {
		this.cab = value;
	}

	public String getBIC() {
		return bic;
	}

	public void setBIC(String value) {
		this.bic = value;
	}

	public BigDecimal getScontoPagamentoAnticipato() {
		return scontoPagamentoAnticipato;
	}

	public void setScontoPagamentoAnticipato(BigDecimal value) {
		this.scontoPagamentoAnticipato = value;
	}

	public XMLGregorianCalendar getDataLimitePagamentoAnticipato() {
		return dataLimitePagamentoAnticipato;
	}

	public void setDataLimitePagamentoAnticipato(XMLGregorianCalendar value) {
		this.dataLimitePagamentoAnticipato = value;
	}

	public BigDecimal getPenalitaPagamentiRitardati() {
		return penalitaPagamentiRitardati;
	}

	public void setPenalitaPagamentiRitardati(BigDecimal value) {
		this.penalitaPagamentiRitardati = value;
	}

	public XMLGregorianCalendar getDataDecorrenzaPenale() {
		return dataDecorrenzaPenale;
	}

	public void setDataDecorrenzaPenale(XMLGregorianCalendar value) {
		this.dataDecorrenzaPenale = value;
	}

	public String getCodicePagamento() {
		return codicePagamento;
	}

	public void setCodicePagamento(String value) {
		this.codicePagamento = value;
	}

}
