//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DettaglioLineeType", propOrder = { "numeroLinea", "tipoCessionePrestazione", "codiceArticolo",
		"descrizione", "quantita", "unitaMisura", "dataInizioPeriodo", "dataFinePeriodo", "prezzoUnitario",
		"scontoMaggiorazione", "prezzoTotale", "aliquotaIVA", "ritenuta", "natura", "riferimentoAmministrazione",
		"altriDatiGestionali" })
public class DettaglioLineeType {

	@XmlElement(name = "NumeroLinea")
	@XmlSchemaType(name = "integer")
	protected int numeroLinea;
	@XmlElement(name = "TipoCessionePrestazione")
	@XmlSchemaType(name = "string")
	protected TipoCessionePrestazioneType tipoCessionePrestazione;
	@XmlElement(name = "CodiceArticolo")
	protected List<CodiceArticoloType> codiceArticolo;
	@XmlElement(name = "Descrizione", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String descrizione;
	@XmlElement(name = "Quantita")
	protected BigDecimal quantita;
	@XmlElement(name = "UnitaMisura")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String unitaMisura;
	@XmlElement(name = "DataInizioPeriodo")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataInizioPeriodo;
	@XmlElement(name = "DataFinePeriodo")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataFinePeriodo;
	@XmlElement(name = "PrezzoUnitario", required = true)
	protected BigDecimal prezzoUnitario;
	@XmlElement(name = "ScontoMaggiorazione")
	protected List<ScontoMaggiorazioneType> scontoMaggiorazione;
	@XmlElement(name = "PrezzoTotale", required = true)
	protected BigDecimal prezzoTotale;
	@XmlElement(name = "AliquotaIVA", required = true)
	protected BigDecimal aliquotaIVA;
	@XmlElement(name = "Ritenuta")
	@XmlSchemaType(name = "string")
	protected RitenutaType ritenuta;
	@XmlElement(name = "Natura")
	@XmlSchemaType(name = "string")
	protected NaturaType natura;
	@XmlElement(name = "RiferimentoAmministrazione")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String riferimentoAmministrazione;
	@XmlElement(name = "AltriDatiGestionali")
	protected List<AltriDatiGestionaliType> altriDatiGestionali;

	public int getNumeroLinea() {
		return numeroLinea;
	}

	public void setNumeroLinea(int value) {
		this.numeroLinea = value;
	}

	public TipoCessionePrestazioneType getTipoCessionePrestazione() {
		return tipoCessionePrestazione;
	}

	public void setTipoCessionePrestazione(TipoCessionePrestazioneType value) {
		this.tipoCessionePrestazione = value;
	}

	public List<CodiceArticoloType> getCodiceArticolo() {
		if (codiceArticolo == null) {
			codiceArticolo = new ArrayList<CodiceArticoloType>();
		}
		return this.codiceArticolo;
	}

	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String value) {
		this.descrizione = value;
	}

	public BigDecimal getQuantita() {
		return quantita;
	}

	public void setQuantita(BigDecimal value) {
		this.quantita = value;
	}

	public String getUnitaMisura() {
		return unitaMisura;
	}

	public void setUnitaMisura(String value) {
		this.unitaMisura = value;
	}

	public XMLGregorianCalendar getDataInizioPeriodo() {
		return dataInizioPeriodo;
	}

	public void setDataInizioPeriodo(XMLGregorianCalendar value) {
		this.dataInizioPeriodo = value;
	}

	public XMLGregorianCalendar getDataFinePeriodo() {
		return dataFinePeriodo;
	}

	public void setDataFinePeriodo(XMLGregorianCalendar value) {
		this.dataFinePeriodo = value;
	}

	public BigDecimal getPrezzoUnitario() {
		return prezzoUnitario;
	}

	public void setPrezzoUnitario(BigDecimal value) {
		this.prezzoUnitario = value;
	}

	public List<ScontoMaggiorazioneType> getScontoMaggiorazione() {
		if (scontoMaggiorazione == null) {
			scontoMaggiorazione = new ArrayList<ScontoMaggiorazioneType>();
		}
		return this.scontoMaggiorazione;
	}

	public BigDecimal getPrezzoTotale() {
		return prezzoTotale;
	}

	public void setPrezzoTotale(BigDecimal value) {
		this.prezzoTotale = value;
	}

	public BigDecimal getAliquotaIVA() {
		return aliquotaIVA;
	}

	public void setAliquotaIVA(BigDecimal value) {
		this.aliquotaIVA = value;
	}

	public RitenutaType getRitenuta() {
		return ritenuta;
	}

	public void setRitenuta(RitenutaType value) {
		this.ritenuta = value;
	}

	public NaturaType getNatura() {
		return natura;
	}

	public void setNatura(NaturaType value) {
		this.natura = value;
	}

	public String getRiferimentoAmministrazione() {
		return riferimentoAmministrazione;
	}

	public void setRiferimentoAmministrazione(String value) {
		this.riferimentoAmministrazione = value;
	}

	public List<AltriDatiGestionaliType> getAltriDatiGestionali() {
		if (altriDatiGestionali == null) {
			altriDatiGestionali = new ArrayList<AltriDatiGestionaliType>();
		}
		return this.altriDatiGestionali;
	}

}
