//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatturaPrincipaleType", propOrder = { "numeroFatturaPrincipale", "dataFatturaPrincipale" })
public class FatturaPrincipaleType {

	@XmlElement(name = "DataFatturaPrincipale", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dataFatturaPrincipale;

	@XmlElement(name = "NumeroFatturaPrincipale", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String numeroFatturaPrincipale;

	public FatturaPrincipaleType() {
	}
	public FatturaPrincipaleType(XMLGregorianCalendar dataFatturaPrincipale, String numeroFatturaPrincipale) {
		this.dataFatturaPrincipale = dataFatturaPrincipale;
		this.numeroFatturaPrincipale = numeroFatturaPrincipale;
	}

	public XMLGregorianCalendar getDataFatturaPrincipale() {
		return dataFatturaPrincipale;
	}

	public String getNumeroFatturaPrincipale() {
		return numeroFatturaPrincipale;
	}

	public void setDataFatturaPrincipale(XMLGregorianCalendar value) {
		this.dataFatturaPrincipale = value;
	}

	public void setNumeroFatturaPrincipale(String value) {
		this.numeroFatturaPrincipale = value;
	}

}
