//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import it.gov.aifa.invoice_processor.mapping.org.w3._2000._09.xmldsig_.SignatureType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatturaElettronicaType", propOrder = { "fatturaElettronicaHeader", "fatturaElettronicaBody",
		"signature" })
public class FatturaElettronicaType {

	@XmlElement(name = "FatturaElettronicaHeader", required = true)
	protected FatturaElettronicaHeaderType fatturaElettronicaHeader;
	@XmlElement(name = "FatturaElettronicaBody", required = true)
	protected List<FatturaElettronicaBodyType> fatturaElettronicaBody;
	@XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
	protected SignatureType signature;
	@XmlAttribute(name = "versione", required = true)
	protected FormatoTrasmissioneType versione;

	public FatturaElettronicaHeaderType getFatturaElettronicaHeader() {
		return fatturaElettronicaHeader;
	}

	public void setFatturaElettronicaHeader(FatturaElettronicaHeaderType value) {
		this.fatturaElettronicaHeader = value;
	}

	public List<FatturaElettronicaBodyType> getFatturaElettronicaBody() {
		if (fatturaElettronicaBody == null) {
			fatturaElettronicaBody = new ArrayList<FatturaElettronicaBodyType>();
		}
		return this.fatturaElettronicaBody;
	}

	public SignatureType getSignature() {
		return signature;
	}

	public void setSignature(SignatureType value) {
		this.signature = value;
	}

	public FormatoTrasmissioneType getVersione() {
		return versione;
	}

	public void setVersione(FormatoTrasmissioneType value) {
		this.versione = value;
	}

}
