//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatturaElettronicaHeaderType", propOrder = { "datiTrasmissione", "cedentePrestatore",
		"rappresentanteFiscale", "cessionarioCommittente", "terzoIntermediarioOSoggettoEmittente",
		"soggettoEmittente" })
public class FatturaElettronicaHeaderType {

	@XmlElement(name = "DatiTrasmissione", required = true)
	protected DatiTrasmissioneType datiTrasmissione;
	@XmlElement(name = "CedentePrestatore", required = true)
	protected CedentePrestatoreType cedentePrestatore;
	@XmlElement(name = "RappresentanteFiscale")
	protected RappresentanteFiscaleType rappresentanteFiscale;
	@XmlElement(name = "CessionarioCommittente", required = true)
	protected CessionarioCommittenteType cessionarioCommittente;
	@XmlElement(name = "TerzoIntermediarioOSoggettoEmittente")
	protected TerzoIntermediarioSoggettoEmittenteType terzoIntermediarioOSoggettoEmittente;
	@XmlElement(name = "SoggettoEmittente")
	@XmlSchemaType(name = "string")
	protected SoggettoEmittenteType soggettoEmittente;

	public DatiTrasmissioneType getDatiTrasmissione() {
		return datiTrasmissione;
	}

	public void setDatiTrasmissione(DatiTrasmissioneType value) {
		this.datiTrasmissione = value;
	}

	public CedentePrestatoreType getCedentePrestatore() {
		return cedentePrestatore;
	}

	public void setCedentePrestatore(CedentePrestatoreType value) {
		this.cedentePrestatore = value;
	}

	public RappresentanteFiscaleType getRappresentanteFiscale() {
		return rappresentanteFiscale;
	}

	public void setRappresentanteFiscale(RappresentanteFiscaleType value) {
		this.rappresentanteFiscale = value;
	}

	public CessionarioCommittenteType getCessionarioCommittente() {
		return cessionarioCommittente;
	}

	public void setCessionarioCommittente(CessionarioCommittenteType value) {
		this.cessionarioCommittente = value;
	}

	public TerzoIntermediarioSoggettoEmittenteType getTerzoIntermediarioOSoggettoEmittente() {
		return terzoIntermediarioOSoggettoEmittente;
	}

	public void setTerzoIntermediarioOSoggettoEmittente(TerzoIntermediarioSoggettoEmittenteType value) {
		this.terzoIntermediarioOSoggettoEmittente = value;
	}

	public SoggettoEmittenteType getSoggettoEmittente() {
		return soggettoEmittente;
	}

	public void setSoggettoEmittente(SoggettoEmittenteType value) {
		this.soggettoEmittente = value;
	}

}
