//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "FormatoTrasmissioneType")
@XmlEnum
public enum FormatoTrasmissioneType {

	@XmlEnumValue("FPA12")
	FPA_12("FPA12"),

	@XmlEnumValue("FPR12")
	FPR_12("FPR12");
	private final String value;

	FormatoTrasmissioneType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static FormatoTrasmissioneType fromValue(String v) {
		for (FormatoTrasmissioneType c : FormatoTrasmissioneType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
