//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdFiscaleType", propOrder = { "idPaese", "idCodice" })
public class IdFiscaleType {

	@XmlElement(name = "IdPaese", required = true)
	protected String idPaese;
	@XmlElement(name = "IdCodice", required = true)
	protected String idCodice;

	public String getIdPaese() {
		return idPaese;
	}

	public void setIdPaese(String value) {
		this.idPaese = value;
	}

	public String getIdCodice() {
		return idCodice;
	}

	public void setIdCodice(String value) {
		this.idCodice = value;
	}

}
