//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndirizzoType", propOrder = { "indirizzo", "numeroCivico", "cap", "comune", "provincia", "nazione" })
public class IndirizzoType {

	@XmlElement(name = "Indirizzo", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String indirizzo;
	@XmlElement(name = "NumeroCivico")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String numeroCivico;
	@XmlElement(name = "CAP", required = true)
	protected String cap;
	@XmlElement(name = "Comune", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String comune;
	@XmlElement(name = "Provincia")
	protected String provincia;
	@XmlElement(name = "Nazione", required = true, defaultValue = "IT")
	protected String nazione;

	public String getIndirizzo() {
		return indirizzo;
	}

	public void setIndirizzo(String value) {
		this.indirizzo = value;
	}

	public String getNumeroCivico() {
		return numeroCivico;
	}

	public void setNumeroCivico(String value) {
		this.numeroCivico = value;
	}

	public String getCAP() {
		return cap;
	}

	public void setCAP(String value) {
		this.cap = value;
	}

	public String getComune() {
		return comune;
	}

	public void setComune(String value) {
		this.comune = value;
	}

	public String getProvincia() {
		return provincia;
	}

	public void setProvincia(String value) {
		this.provincia = value;
	}

	public String getNazione() {
		return nazione;
	}

	public void setNazione(String value) {
		this.nazione = value;
	}

}
