//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IscrizioneREAType", propOrder = { "ufficio", "numeroREA", "capitaleSociale", "socioUnico",
		"statoLiquidazione" })
public class IscrizioneREAType {

	@XmlElement(name = "Ufficio", required = true)
	protected String ufficio;
	@XmlElement(name = "NumeroREA", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@XmlSchemaType(name = "normalizedString")
	protected String numeroREA;
	@XmlElement(name = "CapitaleSociale")
	protected BigDecimal capitaleSociale;
	@XmlElement(name = "SocioUnico")
	@XmlSchemaType(name = "string")
	protected SocioUnicoType socioUnico;
	@XmlElement(name = "StatoLiquidazione", required = true)
	@XmlSchemaType(name = "string")
	protected StatoLiquidazioneType statoLiquidazione;

	public String getUfficio() {
		return ufficio;
	}

	public void setUfficio(String value) {
		this.ufficio = value;
	}

	public String getNumeroREA() {
		return numeroREA;
	}

	public void setNumeroREA(String value) {
		this.numeroREA = value;
	}

	public BigDecimal getCapitaleSociale() {
		return capitaleSociale;
	}

	public void setCapitaleSociale(BigDecimal value) {
		this.capitaleSociale = value;
	}

	public SocioUnicoType getSocioUnico() {
		return socioUnico;
	}

	public void setSocioUnico(SocioUnicoType value) {
		this.socioUnico = value;
	}

	public StatoLiquidazioneType getStatoLiquidazione() {
		return statoLiquidazione;
	}

	public void setStatoLiquidazione(StatoLiquidazioneType value) {
		this.statoLiquidazione = value;
	}

}
