//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "ModalitaPagamentoType")
@XmlEnum
public enum ModalitaPagamentoType {

	@XmlEnumValue("MP01")
	MP_01("MP01"),

	@XmlEnumValue("MP02")
	MP_02("MP02"),

	@XmlEnumValue("MP03")
	MP_03("MP03"),

	@XmlEnumValue("MP04")
	MP_04("MP04"),

	@XmlEnumValue("MP05")
	MP_05("MP05"),

	@XmlEnumValue("MP06")
	MP_06("MP06"),

	@XmlEnumValue("MP07")
	MP_07("MP07"),

	@XmlEnumValue("MP08")
	MP_08("MP08"),

	@XmlEnumValue("MP09")
	MP_09("MP09"),

	@XmlEnumValue("MP10")
	MP_10("MP10"),

	@XmlEnumValue("MP11")
	MP_11("MP11"),

	@XmlEnumValue("MP12")
	MP_12("MP12"),

	@XmlEnumValue("MP13")
	MP_13("MP13"),

	@XmlEnumValue("MP14")
	MP_14("MP14"),

	@XmlEnumValue("MP15")
	MP_15("MP15"),

	@XmlEnumValue("MP16")
	MP_16("MP16"),

	@XmlEnumValue("MP17")
	MP_17("MP17"),

	@XmlEnumValue("MP18")
	MP_18("MP18"),

	@XmlEnumValue("MP19")
	MP_19("MP19"),

	@XmlEnumValue("MP20")
	MP_20("MP20"),

	@XmlEnumValue("MP21")
	MP_21("MP21"),

	@XmlEnumValue("MP22")
	MP_22("MP22");
	private final String value;

	ModalitaPagamentoType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static ModalitaPagamentoType fromValue(String v) {
		for (ModalitaPagamentoType c : ModalitaPagamentoType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
