//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScontoMaggiorazioneType", propOrder = { "tipo", "percentuale", "importo" })
public class ScontoMaggiorazioneType {

	@XmlElement(name = "Tipo", required = true)
	@XmlSchemaType(name = "string")
	protected TipoScontoMaggiorazioneType tipo;
	@XmlElement(name = "Percentuale")
	protected BigDecimal percentuale;
	@XmlElement(name = "Importo")
	protected BigDecimal importo;

	public TipoScontoMaggiorazioneType getTipo() {
		return tipo;
	}

	public void setTipo(TipoScontoMaggiorazioneType value) {
		this.tipo = value;
	}

	public BigDecimal getPercentuale() {
		return percentuale;
	}

	public void setPercentuale(BigDecimal value) {
		this.percentuale = value;
	}

	public BigDecimal getImporto() {
		return importo;
	}

	public void setImporto(BigDecimal value) {
		this.importo = value;
	}

}
