//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "TipoCassaType")
@XmlEnum
public enum TipoCassaType {

	@XmlEnumValue("TC01")
	TC_01("TC01"),

	@XmlEnumValue("TC02")
	TC_02("TC02"),

	@XmlEnumValue("TC03")
	TC_03("TC03"),

	@XmlEnumValue("TC04")
	TC_04("TC04"),

	@XmlEnumValue("TC05")
	TC_05("TC05"),

	@XmlEnumValue("TC06")
	TC_06("TC06"),

	@XmlEnumValue("TC07")
	TC_07("TC07"),

	@XmlEnumValue("TC08")
	TC_08("TC08"),

	@XmlEnumValue("TC09")
	TC_09("TC09"),

	@XmlEnumValue("TC10")
	TC_10("TC10"),

	@XmlEnumValue("TC11")
	TC_11("TC11"),

	@XmlEnumValue("TC12")
	TC_12("TC12"),

	@XmlEnumValue("TC13")
	TC_13("TC13"),

	@XmlEnumValue("TC14")
	TC_14("TC14"),

	@XmlEnumValue("TC15")
	TC_15("TC15"),

	@XmlEnumValue("TC16")
	TC_16("TC16"),

	@XmlEnumValue("TC17")
	TC_17("TC17"),

	@XmlEnumValue("TC18")
	TC_18("TC18"),

	@XmlEnumValue("TC19")
	TC_19("TC19"),

	@XmlEnumValue("TC20")
	TC_20("TC20"),

	@XmlEnumValue("TC21")
	TC_21("TC21"),

	@XmlEnumValue("TC22")
	TC_22("TC22");
	public static TipoCassaType fromValue(String v) {
		for (TipoCassaType c : TipoCassaType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

	private final String value;

	TipoCassaType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

}
