//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "TipoDocumentoType")
@XmlEnum
public enum TipoDocumentoType {

	@XmlEnumValue("TD01")
	TD_01("TD01"),

	@XmlEnumValue("TD02")
	TD_02("TD02"),

	@XmlEnumValue("TD03")
	TD_03("TD03"),

	@XmlEnumValue("TD04")
	TD_04("TD04"),

	@XmlEnumValue("TD05")
	TD_05("TD05"),

	@XmlEnumValue("TD06")
	TD_06("TD06");
	private final String value;

	TipoDocumentoType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static TipoDocumentoType fromValue(String v) {
		for (TipoDocumentoType c : TipoDocumentoType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
