//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "TipoRitenutaType")
@XmlEnum
public enum TipoRitenutaType {

	@XmlEnumValue("RT01")
	RT_01("RT01"),

	@XmlEnumValue("RT02")
	RT_02("RT02");
	private final String value;

	TipoRitenutaType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static TipoRitenutaType fromValue(String v) {
		for (TipoRitenutaType c : TipoRitenutaType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
