//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

package it.gov.aifa.invoice_processor.mapping.invoice1_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatturaElettronicaBodyType", propOrder = { "datiGenerali", "datiBeniServizi", "datiVeicoli",
		"datiPagamento", "allegati" })
public class FatturaElettronicaBodyType {

	@XmlElement(name = "Allegati")
	protected List<AllegatiType> allegati;

	@XmlElement(name = "DatiBeniServizi", required = true)
	protected DatiBeniServiziType datiBeniServizi;

	@XmlElement(name = "DatiGenerali", required = true)
	protected DatiGeneraliType datiGenerali;
	@XmlElement(name = "DatiPagamento")
	protected List<DatiPagamentoType> datiPagamento;
	@XmlElement(name = "DatiVeicoli")
	protected DatiVeicoliType datiVeicoli;
	public FatturaElettronicaBodyType() {
	}
	public FatturaElettronicaBodyType(List<AllegatiType> allegati, DatiBeniServiziType datiBeniServizi,
			DatiGeneraliType datiGenerali, List<DatiPagamentoType> datiPagamento, DatiVeicoliType datiVeicoli) {
		this.allegati = allegati;
		this.datiBeniServizi = datiBeniServizi;
		this.datiGenerali = datiGenerali;
		this.datiPagamento = datiPagamento;
		this.datiVeicoli = datiVeicoli;
	}

	public List<AllegatiType> getAllegati() {
		if (allegati == null) {
			allegati = new ArrayList<AllegatiType>();
		}
		return this.allegati;
	}

	public DatiBeniServiziType getDatiBeniServizi() {
		return datiBeniServizi;
	}

	public DatiGeneraliType getDatiGenerali() {
		return datiGenerali;
	}

	public List<DatiPagamentoType> getDatiPagamento() {
		if (datiPagamento == null) {
			datiPagamento = new ArrayList<DatiPagamentoType>();
		}
		return this.datiPagamento;
	}

	public DatiVeicoliType getDatiVeicoli() {
		return datiVeicoli;
	}

	public void setDatiBeniServizi(DatiBeniServiziType value) {
		this.datiBeniServizi = value;
	}

	public void setDatiGenerali(DatiGeneraliType value) {
		this.datiGenerali = value;
	}

	public void setDatiVeicoli(DatiVeicoliType value) {
		this.datiVeicoli = value;
	}

}
