//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.16 at 02:40:54 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2")
package it.gov.aifa.invoice_processor.mapping.invoice1_2;
